default_platform(:ios)

SCHEMES = { ios: 'WWDC', tvos: 'WWDC_tvOS' }.freeze

default_platform(:ios)

[:ios, :tvos].each do |current_platform|
  # Define all lanes we wanna run here
  platform current_platform do
    # Get dependencies
    scheme = SCHEMES[current_platform]

    desc "Run unit tests"
    lane :test do
      scan(scheme: scheme)
      clean_build_artifacts
    end

  end
end

# Global lanes to run on all platforms
desc "Runs unit tests on both iOS and tvOS"
lane :test_all do
  ['ios', 'tvos'].each do |platform|
    Fastlane::LaneManager.cruise_lane(platform, 'test')
  end
end
